src/Entity/Inspection.php
<?php

namespace App\Entity;

use App\Repository\InspectionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InspectionRepository::class)
 */
class Inspection extends BaseEntity
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $heading;

    /**
     * @ORM\OneToMany(targetEntity=SubStep::class, mappedBy="inspection")
     */
    private $Substeps;

    public function __construct()
    {
        parent::__construct();
        $this->Substeps = new ArrayCollection();
    }

    public function __toString():string
    {
        return $this->getHeading();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHeading(): ?string
    {
        return $this->heading;
    }

    public function setHeading(string $heading): self
    {
        $this->heading = $heading;

        return $this;
    }

    /**
     * @return Collection<int, SubStep>
     */
    public function getSubsteps(): Collection
    {
        return $this->Substeps;
    }

    public function addSubstep(SubStep $substep): self
    {
        if (!$this->Substeps->contains($substep)) {
            $this->Substeps[] = $substep;
            $substep->setInspection($this);
        }

        return $this;
    }


    public function removeSubstep(SubStep $substep): self
    {
        if ($this->Substeps->removeElement($substep)) {
            // set the owning side to null (unless already changed)
            if ($substep->getInspection() === $this) {
                $substep->setInspection(null);
            }
        }

        return $this;
    }
}

src/Form/InspectionType.php
<?php

namespace App\Form;

use App\Entity\Inspection;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InspectionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
//            ->add('createdAt')
//            ->add('updatedAt')
//            ->add('deletedAt')
//            ->add('identifier')
            ->add('heading', TextType::class, [
                'label' => 'Heading'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inspection::class,
        ]);
    }
}

src/Controller/InspectionController.php
<?php

namespace App\Controller;

use App\Entity\Inspection;
use App\Form\InspectionType;
use App\Repository\InspectionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/inspection")
 */
class InspectionController extends AbstractController
{
    /**
     * @Route("/", name="inspection_index", methods={"GET"})
     */
    public function index(InspectionRepository $inspectionRepository): Response
    {
        return $this->render('inspection/index.html.twig', [
            'inspections' => $inspectionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="inspection_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $inspection = new Inspection();
        $form = $this->createForm(InspectionType::class, $inspection);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($inspection);
            $entityManager->flush();

            return $this->redirectToRoute('inspection_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inspection/new.html.twig', [
            'inspection' => $inspection,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="inspection_show", methods={"GET"})
     */
    public function show(Inspection $inspection): Response
    {
        return $this->render('inspection/show.html.twig', [
            'inspection' => $inspection,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="inspection_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Inspection $inspection, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InspectionType::class, $inspection);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('inspection_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inspection/edit.html.twig', [
            'inspection' => $inspection,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="inspection_delete", methods={"POST"})
     */
    public function delete(Request $request, Inspection $inspection, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inspection->getId(), $request->request->get('_token'))) {
            $entityManager->remove($inspection);
            $entityManager->flush();
        }

        return $this->redirectToRoute('inspection_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inspection/_delete_form.html.twig
<form method="post" action="{{ path('inspection_delete', {'id': inspection.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inspection.id) }}">
    <button class="btn">Delete</button>
</form>

templates/inspection/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button  class="float-end btn btn-sm btn-light mx-2 my-2">{{ button_label|default('Save') }}</button>
<a  class="float-end btn btn-sm btn-light mx-2 my-2" href="{{ path('inspection_index') }}">Cancel</a>
{{ form_end(form) }}

templates/inspection/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Inspection{% endblock %}

{% block body %}
    <h1>Edit Inspection</h1>

    {{ include('inspection/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('inspection_index') }}">back to list</a>

    {{ include('inspection/_delete_form.html.twig') }}
{% endblock %}

templates/inspection/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inspection index{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Inspection</h1>
        </div>
        <div class="col">
            <a  class="float-end btn btn-sm btn-success" href="{{ path('inspection_new') }}">New Inspection</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Heading</th>
                <th>Sub Steps</th>
                <th>CreatedAt</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
        {% for inspection in inspections %}
            <tr>
                <td>{{ inspection.heading }}</td>
                <td><a href="{{ path('sub_step_index' , {'identifier' : inspection.identifier}) }}">
                        {{ inspection.substeps|length }}
                    </a></td>
                <td>{{ inspection.createdAt ? inspection.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td><a class="btn btn-sm btn-primary" href="{{ path('inspection_edit', {'id': inspection.id}) }}">edit</a></td>
                <td><form method="post" action="{{ path('inspection_delete', {'id': inspection.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inspection.id) }}">
                        <button class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/inspection/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inspection Details{% endblock %}

{% block body %}
    <h1>Inspection Details</h1>

    {{ include('inspection/_form.html.twig') }}


{% endblock %}

templates/inspection/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inspection{% endblock %}

{% block body %}
    <h1>Inspection</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>CreatedAt</th>
                <td>{{ inspection.createdAt ? inspection.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ inspection.updatedAt ? inspection.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DeletedAt</th>
                <td>{{ inspection.deletedAt ? inspection.deletedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Identifier</th>
                <td>{{ inspection.identifier }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ inspection.id }}</td>
            </tr>
            <tr>
                <th>Heading</th>
                <td>{{ inspection.heading }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('inspection_index') }}">back to list</a>

    <a href="{{ path('inspection_edit', {'id': inspection.id}) }}">edit</a>

    {{ include('inspection/_delete_form.html.twig') }}
{% endblock %}